packages:
  - ansible
  - arch-install-scripts
  - baobab
  - base
  - base-devel
  - bash-completion
  - bat
  - bc
  - chafa
  - docker
  - epiphany
  - evince
  - exo
  - fakeroot-tcp
  - fd
  - firefox
  - fzf
  - garcon
  - gdm
  - ghostty
  - git
  - gnome-backgrounds
  - gnome-calculator
  - gnome-calendar
  - gnome-characters
  - gnome-clocks
  - gnome-color-manager
  - gnome-connections
  - gnome-console
  - gnome-contacts
  - gnome-control-center
  - gnome-disk-utility
  - gnome-font-viewer
  - gnome-keyring
  - gnome-logs
  - gnome-maps
  - gnome-menus
  - gnome-music
  - gnome-remote-desktop
  - gnome-session
  - gnome-settings-daemon
  - gnome-shell
  - gnome-shell-extensions
  - gnome-software
  - gnome-system-monitor
  - gnome-text-editor
  - gnome-tour
  - gnome-user-docs
  - gnome-user-share
  - gnome-weather
  - go
  - gopls
  - grilo-plugins
  - grub
  - gst-plugin-pipewire
  - gvfs
  - gvfs-afc
  - gvfs-dnssd
  - gvfs-goa
  - gvfs-google
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-onedrive
  - gvfs-smb
  - gvfs-wsdd
  - intel-ucode
  - iwd
  - jq
  - lazygit
  - less
  - libpulse
  - linux
  - linux-firmware
  - loupe
  - lua-language-server
  - malcontent
  - nano
  - nautilus
  - neovim
  - networkmanager
  - nomad
  - npm
  - openssh
  - orca
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - playerctl
  - postgresql
  - pyright
  - ripgrep
  - rygel
  - simple-scan
  - snapshot
  - stylua
  - sudo
  - sushi
  - sway
  - tecla
  - thunar
  - thunar-volman
  - tmux
  - totem
  - tumbler
  - vagrant
  - vim
  - virtualbox
  - weston
  - wget
  - wireplumber
  - wlroots
  - xclip
  - xdg-desktop-portal-gnome
  - xdg-user-dirs-gtk
  - xf86-video-vesa
  - xfce4-appfinder
  - xfce4-panel
  - xfce4-power-manager
  - xfce4-session
  - xfce4-settings
  - xfce4-terminal
  - xfconf
  - xfdesktop
  - xfwm4
  - xfwm4-themes
  - xorg-bdftopcf
  - xorg-docs
  - xorg-font-util
  - xorg-fonts-100dpi
  - xorg-fonts-75dpi
  - xorg-iceauth
  - xorg-mkfontscale
  - xorg-server
  - xorg-server-devel
  - xorg-server-xephyr
  - xorg-server-xnest
  - xorg-server-xvfb
  - xorg-sessreg
  - xorg-smproxy
  - xorg-x11perf
  - xorg-xauth
  - xorg-xbacklight
  - xorg-xclock
  - xorg-xcmsdb
  - xorg-xcursorgen
  - xorg-xdpyinfo
  - xorg-xdriinfo
  - xorg-xev
  - xorg-xgamma
  - xorg-xhost
  - xorg-xinput
  - xorg-xkbevd
  - xorg-xkbprint
  - xorg-xkbutils
  - xorg-xkill
  - xorg-xlsatoms
  - xorg-xlsclients
  - xorg-xpr
  - xorg-xrandr
  - xorg-xrefresh
  - xorg-xsetroot
  - xorg-xvinfo
  - xorg-xwd
  - xorg-xwininfo
  - xorg-xwud
  - yelp
  - zellij
  - zig
  - zls
  - zram-generator
