---
- name: Create directories
  hosts: all
  become: false
  tasks:
    - name: Load directory list
      include_vars:
        file: "../config/directories.yml"

    - name: Ensure directories exist
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ directories }}"
      when: directories | length > 0

    - name: No directories to create
      debug:
        msg: "No directories defined in the configuration file."
      when: directories | length == 0
