---
- name: Update the System on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Synchronize package databases
      apt:
        update_cache: yes

    - name: Upgrade all installed packages
      apt:
        upgrade: yes
